-- Step 2: Create the 'positions' (breakdown) table
CREATE TABLE public.positions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  symbol text NOT NULL,
  quantity numeric NOT NULL,
  average_cost numeric NOT NULL,
  updated_at timestamptz DEFAULT now(),
  -- Ensures one row per user/symbol combination
  CONSTRAINT positions_user_symbol_key UNIQUE (user_id, symbol)
);

-- RLS for positions
ALTER TABLE public.positions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own positions"
  ON public.positions FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- Step 3: Create the 'investment_history' table (for the chart)
CREATE TABLE public.investment_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  snapshot_date date NOT NULL,
  total_worth numeric NOT NULL,
  total_invested numeric NOT NULL,
  unrealized_pnl numeric NOT NULL,
  -- Ensures one snapshot per user, per day
  CONSTRAINT investment_history_user_date_key UNIQUE (user_id, snapshot_date)
);


-- Re-create the view WITHOUT any policy
CREATE VIEW public.portfolios AS
SELECT
  p.user_id,
  COALESCE(array_agg(p.symbol) FILTER (WHERE p.quantity > 0), '{}') AS tickers,
  COALESCE(sum(p.quantity * s.current_price), 0) AS total_worth,
  COALESCE(sum(p.quantity * p.average_cost), 0) AS total_invested,
  COALESCE(sum(p.quantity * (s.current_price - p.average_cost)), 0) AS unrealized_pnl,
  CASE
    WHEN COALESCE(sum(p.quantity * p.average_cost), 0) = 0 THEN 0
    ELSE COALESCE(sum(p.quantity * (s.current_price - p.average_cost)), 0) / sum(p.quantity * p.average_cost)
  END AS total_change_pct,
  CASE
    WHEN COALESCE(sum(p.quantity * s.prev_close), 0) = 0 THEN 0
    ELSE (COALESCE(sum(p.quantity * s.current_price), 0) - sum(p.quantity * s.prev_close)) / sum(p.quantity * s.prev_close)
  END AS last_change_pct,
  count(*) FILTER (WHERE p.quantity > 0) AS position_count,
  max(p.updated_at) as last_trade_at,
  now() as updated_at
FROM
  public.positions p
  LEFT JOIN public.symbols s ON p.symbol = s.symbol
GROUP BY
  p.user_id;

